services:
  redis:
    image: redis:alpine
    container_name: gnomo-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --requirepass gnomo123

volumes:
  redis_data:
